### ISSUE TITLE
Create index in Splunk Master

### ISSUE THREAD

**Issue by atilaloise** [atilaloise/ansible_splunk_index#1]
Option to pass the master url to config cluster indexes and push it to indexes.

 ```
host:
      description: Splunk host where de index should be created. If it's a index cluster, point to the master here.Defaults to localhost
      required: true
      type: str
push_bundle:
        description: Set to true if this index will be setup in a index master. Attention!! Removing index  needs indexer restart. defaults to False
        required: false
        type: bool
```
